title: Bioinformatics Documents 
description: A repository for bioinformatics documentation 
theme: just-the-docs

url: https://pirbright-bioinformatics.github.io/Documentation
nav_enabled: true


#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
